# LAB 01 – Báo cáo mô tả bộ dữ liệu bài báo khoa học

**Nguồn:** OpenAlex API  
**Cách thu thập:** Tìm kiếm theo 6 nhóm từ khóa, lấy tối đa 25 bài/nhóm.
**Mục đích:** Giới thiệu sơ bộ bộ dữ liệu và thống kê mô tả cơ bản.

In [4]:
import pandas as pd
from pathlib import Path

base_dir = Path.cwd()
if not (base_dir / "data" / "raw" / "research_papers_raw.csv").exists():
    base_dir = base_dir.parent
path = base_dir / "data" / "raw" / "research_papers_raw.csv"
df = pd.read_csv(path)
print("Số dòng:", df.shape[0], "| Số cột:", df.shape[1])
display(df.head())

Số dòng: 150 | Số cột: 18

,paper_id,title,query_field,field,authors,pub_year,venue,publisher,publication_type,citations,abstract,doi,language,open_access,scholar_search_url,collected_at,source_database,source_url
0,https://openalex.org/W3153990350,Machine learning and deep learning,Computer Science & AI,Computer Science,Christian Janiesch; Patrick Zschech; Kai Heinrich,2021,Electronic Markets,Springer Science+Business Media,article,2655,"Abstract Today, intelligent systems that offer...",https://doi.org/10.1007/s12525-021-00475-2,en,True,https://scholar.google.com/scholar?q=%22Machin...,2026-10-11T07:19:18.803025+00:00,OpenAlex,https://openalex.org/W3153990350
1,https://openalex.org/W3208674021,Machine Learning,Computer Science & AI,Computer Science,Ethem Alpaydın,2021,The MIT Press eBooks,The MIT Press,book,374,A concise overview of machine learning—compute...,https://doi.org/10.7551/mitpress/13811.001.0001,en,True,https://scholar.google.com/scholar?q=%22Machin...,2026-10-11T07:19:18.803025+00:00,OpenAlex,https://openalex.org/W3208674021
2,https://openalex.org/W2751318774,Introduction to Machine Learning,Computer Science & AI,Computer Science,NaN,2019,Series in machine perception and artificial in...,World Scientific,book-chapter,1648,The goal of machine learning is to program com...,https://doi.org/10.1142/9789811201967_0001,en,False,https://scholar.google.com/scholar?q=%22Introd...,2026-10-11T07:19:18.803025+00:00,OpenAlex,https://openalex.org/W2751318774
3,https://openalex.org/W2562618250,Python Machine Learning,Computer Science & AI,Computer Science,Sebastian Raschka,2015,NaN,NaN,book,649,Unlock deeper insights into Machine Leaning wi...,NaN,en,False,https://scholar.google.com/scholar?q=%22Python...,2026-10-11T07:19:18.803025+00:00,OpenAlex,https://openalex.org/W2562618250
4,https://openalex.org/W3010521003,An Introduction to Machine Learning,Computer Science & AI,Computer Science,Solveig Badillo; Balázs Bánfai; Fabian Birzele...,2020,Clinical Pharmacology & Therapeutics,Wiley,article,802,"In the last few years, machine learning (ML) a...",https://doi.org/10.1002/cpt.1796,en,True,https://scholar.google.com/scholar?q=%22An+Int...,2026-10-11T07:19:18.803025+00:00,OpenAlex,https://openalex.org/W3010521003

## 1. Mô tả thuộc tính

| Thuộc tính | Ý nghĩa |
|---|---|
| paper_id | Mã OpenAlex của bài báo |
| title | Tiêu đề |
| query_field | Nhóm từ khóa được dùng để tìm bài |
| field | Lĩnh vực chính theo OpenAlex |
| authors | Danh sách tác giả |
| pub_year | Năm công bố |
| venue | Tạp chí/hội nghị/nguồn công bố |
| publisher | Tên tổ chức xuất bản (nếu có) |
| publication_type | Loại công trình |
| citations | Số lượt trích dẫn theo OpenAlex tại thời điểm thu thập |
| abstract | Tóm tắt |
| doi | Mã DOI |
| language | Ngôn ngữ |
| open_access | Có truy cập mở hay không |
| scholar_search_url | URL tìm theo tiêu đề trên Google Scholar |
| collected_at | Thời điểm thu thập |
| source_database | Cơ sở dữ liệu nguồn |
| source_url | URL bản ghi OpenAlex |

In [5]:
print("\nThông tin cấu trúc:")
df.info()
print("\nSố giá trị thiếu:")
display(df.isna().sum().to_frame("missing_count"))
print("\nSố dòng trùng hoàn toàn:", df.duplicated().sum())
print("Số paper_id trùng:", df["paper_id"].duplicated().sum())

Thông tin cấu trúc:
<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   paper_id            150 non-null    str
 1   title               150 non-null    str
 2   query_field         150 non-null    str
 3   field               143 non-null    str
 4   authors             137 non-null    str
 5   pub_year            150 non-null    int64
 6   venue               118 non-null    str
 7   publisher           103 non-null    str
 8   publication_type    150 non-null    str
 9   citations           150 non-null    int64
 10  abstract            150 non-null    str
 11  doi                 121 non-null    str
 12  language            141 non-null    str
 13  open_access         150 non-null    bool
 14  scholar_search_url  150 non-null    str
 15  collected_at        150 non-null    str
 16  source_database     150 non-null    str
 17  source_url          150 non-null    str
dtypes: bool(1), int64(2), str(15)
memory usage: 20.2 KB

Số giá trị thiếu:

                    missing_count
paper_id                        0
title                           0
query_field                     0
field                           7
authors                        13
pub_year                        0
venue                          32
publisher                      47
publication_type                0
citations                       0
abstract                        0
doi                            29
language                        9
open_access                     0
scholar_search_url              0
collected_at                    0
source_database                 0
source_url                      0

Số dòng trùng hoàn toàn: 0
Số paper_id trùng: 0

In [6]:
print("Số bài theo nhóm truy vấn:")
display(df["query_field"].value_counts().to_frame("so_bai"))
print("Số bài theo năm:")
display(df["pub_year"].value_counts().sort_index().to_frame("so_bai"))
print("Thống kê citations:")
display(df["citations"].describe())

Số bài theo nhóm truy vấn:

                          so_bai
query_field
Computer Science & AI         25
Medicine & Healthcare         25
Environmental Science         25
Economics & Business          25
Engineering & Technology      25
Psychology & Education        25

Số bài theo năm:

          so_bai
pub_year
2015          19
2016          15
2017           8
2018          10
2019          21
2020          25
2021          10
2022           8
2023          12
2024          14
2025           5
2026           3

Thống kê citations:

count     150.000000
mean      547.386667
std      1278.903483
min         0.000000
25%         0.000000
50%        80.500000
75%       408.250000
max      9971.000000
Name: citations, dtype: float64

## 2. Nhận xét và kết luận

Sau khi chạy Notebook, điền các kết quả thực tế:

- Bộ dữ liệu gồm **150 dòng** và **18 cột**
- Số bài ở mỗi nhóm truy vấn: **25**.
- Số bản ghi trùng theo `paper_id`: **0**
- Các cột có dữ liệu thiếu nhiều nhất: **publisher**, **doi**, **venue**.

**Kết luận:** Đã thu thập và mô tả bộ dữ liệu nghiên cứu khoa học từ OpenAlex. Dữ liệu phục vụ bài thực hành về thu thập và thống kê cơ bản; không đại diện ngẫu nhiên cho toàn bộ các công trình nghiên cứu.